// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4O_d_doksZhgX1-3cyHUcokGMv2-tZLc',
    appId: '1:233026334032:web:a9b3c3de32c44795a5d055',
    messagingSenderId: '233026334032',
    projectId: 'insta-clone-c3e8c',
    authDomain: 'insta-clone-c3e8c.firebaseapp.com',
    storageBucket: 'insta-clone-c3e8c.firebasestorage.app',
    measurementId: 'G-TXPHZ3J1R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-svQUhBSg33l2YfFGL8vmGIBA1jPo4Y',
    appId: '1:233026334032:android:77a2dc6802ab9467a5d055',
    messagingSenderId: '233026334032',
    projectId: 'insta-clone-c3e8c',
    storageBucket: 'insta-clone-c3e8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4o_Rp2Rv_5dAynTglo_4G9-ueXyYYGPw',
    appId: '1:233026334032:ios:ef528265538a6bdba5d055',
    messagingSenderId: '233026334032',
    projectId: 'insta-clone-c3e8c',
    storageBucket: 'insta-clone-c3e8c.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );
}
